# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ee2ee3d24a2e50463fe7dde5b25ba8f51ae98fa854f1888435d709b3fdb04dc81678c320b78f45724ceca46243ca6f6c4da639b72ed251e8d600fb98ec99594

test:
  secret_key_base: 123a6bb7bf6487d03bae9eef30a51ff59a8f5b56f1a03e41767e3000c07f76404b4321453cb5c9d604c25405b68c36dc1103e0c3facd8b53fff2cdcc5f2ee16d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
